cmake_minimum_required (VERSION 3.8.0 FATAL_ERROR)

if (DEFINED ENV{HASILWGDF_TOOLCHAIN_RAN})
  return ()
endif ()
set (ENV{HASILWGDF_TOOLCHAIN_RAN} true)
list (APPEND HASILWGDF_SUPPORTED_PLATFORMS
    "Android"
    "iOS"
    "Linux"
    "macOS"
    "UWP"
    "Windows"
)
list (APPEND HASILWGDF_SUPPORTED_PLATFORM_VARIATIONS
    "AppleSimulator" "AppleOS" "AppleAll"
    "WinPhone10" "WinPhone8_1" "WinStore10" "WinStore8_1"
    "Windows10" "Windows8_1"
)
set (CURRENT_GEN ${CMAKE_GENERATOR})
set (HASILWGDF_PLATFORM "" CACHE STRING "The platform you want to build for.")
list (FIND HASILWGDF_SUPPORTED_PLATFORMS ${HASILWGDF_PLATFORM} HASILWGDF_PLATFORM_INDEX)
set (HASILWGDF_PLATFORM_VARIANT "" CACHE STRING "The variation of a platform you want to build for (Applicable for specific platforms).")
list (FIND HASILWGDF_SUPPORTED_PLATFORM_VARIATIONS ${HASILWGDF_PLATFORM_VARIANT} HASILWGDF_PLATFORM_VARIANT_INDEX)
if (HASILWGDF_PLATFORM_INDEX EQUAL -1)
  message (FATAL_ERROR "Unsupported platform specified. Please choose from: ${HASILWGDF_SUPPORTED_PLATFORMS}")
endif ()
if (HASILWGDF_PLATFORM_VARIANT_INDEX EQUAL -1)
  message (FATAL_ERROR "Unsupported platform variation specified. Please choose from: ${HASILWGDF_SUPPORTED_PLATFORM_VARIATIONS}")
endif ()
message ("Configuring for platform: ${HASILWGDF_PLATFORM}")

if (${CURRENT_GEN} STREQUAL "Ninja")
  if (HASILWGDF_PLATFORM STREQUAL "Android")
    set (CMAKE_SYSTEM_NAME "Android")
  elseif (HASILWGDF_PLATFORM STREQUAL "Linux")
    set (CMAKE_SYSTEM_NAME "Linux")
  elseif (HASILWGDF_PLATFORM STREQUAL "iOS")
    set (CMAKE_SYSTEM_NAME "iOS")
    if (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleSimulator")
      set (CMAKE_OSX_SYSROOT "iphonesimulator")
    elseif (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleOS")
      set (CMAKE_OSX_SYSROOT "iphoneos")
    elseif (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleAll")
      set (CMAKE_IOS_INSTALL_COMBINED YES)
    else ()
      message (FATAL_ERROR "Variation \"${HASILWGDF_PLATFORM_VARIANT}\" for platform \"${HASILWGDF_PLATFORM}\" is not supported.")
    endif ()
  elseif (HASILWGDF_PLATFORM STREQUAL "macOS")
    set (CMAKE_SYSTEM_NAME "Darwin")
    if (HASILWGDF_PLATFORM_VARIANT NOT STREQUAL "")
      message (FATAL_ERROR "Variation \"${HASILWGDF_PLATFORM_VARIANT}\" for platform \"${HASILWGDF_PLATFORM}\" is not supported.")
    endif ()
  elseif (HASILWGDF_PLATFORM STREQUAL "Windows")
    set (CMAKE_SYSTEM_NAME "Windows")
  else ()
    message (FATAL_ERROR "Unable to use generator \"${CURRENT_GEN}\" with platform \"${HASILWGDF_PLATFORM}\".")
  endif ()
elseif (${CURRENT_GEN} STREQUAL "MinGW Makefiles" AND CMAKE_HOST_WIN32)
  if (HASILWGDF_PLATFORM STREQUAL "Windows")
    set (CMAKE_SYSTEM_NAME "Windows")
  else ()
    message (FATAL_ERROR "Unable to use generator \"${CURRENT_GEN}\" with platform \"${HASILWGDF_PLATFORM}\".")
  endif ()
elseif (${CURRENT_GEN} STREQUAL "MSYS Makefiles" AND CMAKE_HOST_WIN32)
  if (HASILWGDF_PLATFORM STREQUAL "Windows")
    set (CMAKE_SYSTEM_NAME "Windows")
  else ()
    message (FATAL_ERROR "Unable to use generator \"${CURRENT_GEN}\" with platform \"${HASILWGDF_PLATFORM}\".")
  endif ()
elseif (${CURRENT_GEN} STREQUAL "Unix Makefiles" AND CMAKE_HOST_APPLE)
  if (HASILWGDF_PLATFORM STREQUAL "iOS")
    set (CMAKE_SYSTEM_NAME "iOS")
    if (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleSimulator")
      set (CMAKE_OSX_SYSROOT "iphonesimulator")
    elseif (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleOS")
      set (CMAKE_OSX_SYSROOT "iphoneos")
    elseif (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleAll")
      set (CMAKE_IOS_INSTALL_COMBINED YES)
    else ()
      message (FATAL_ERROR "Variation \"${HASILWGDF_PLATFORM_VARIANT}\" for platform \"${HASILWGDF_PLATFORM}\" is not supported.")
    endif ()
  elseif (HASILWGDF_PLATFORM STREQUAL "macOS")
    set (CMAKE_SYSTEM_NAME "Darwin")
    if (HASILWGDF_PLATFORM_VARIANT NOT STREQUAL "")
      message (FATAL_ERROR "Variation \"${HASILWGDF_PLATFORM_VARIANT}\" for platform \"${HASILWGDF_PLATFORM}\" is not supported.")
    endif ()
  else ()
    message (FATAL_ERROR "Unable to use generator \"${CURRENT_GEN}\" with platform \"${HASILWGDF_PLATFORM}\".")
  endif ()
elseif (${CURRENT_GEN} STREQUAL "Unix Makefiles" AND CMAKE_HOST_UNIX)
  if (HASILWGDF_PLATFORM STREQUAL "Android")
    set (CMAKE_SYSTEM_NAME "Android")
  elseif (HASILWGDF_PLATFORM STREQUAL "Linux")
    set (CMAKE_SYSTEM_NAME "Linux")
  endif ()
elseif (${CURRENT_GEN} MATCHES "Visual Studio" AND CMAKE_HOST_WIN32)
  if (HASILWGDF_PLATFORM STREQUAL "UWP")
  elseif (HASILWGDF_PLATFORM STREQUAL "Windows")
    set (CMAKE_SYSTEM_NAME "Windows")
  else ()
    message (FATAL_ERROR "Unable to use generator \"${CURRENT_GEN}\" with platform \"${HASILWGDF_PLATFORM}\".")
  endif ()
elseif (${CURRENT_GEN} STREQUAL "Xcode" AND CMAKE_HOST_APPLE)
  if (HASILWGDF_PLATFORM STREQUAL "iOS")
    set (CMAKE_SYSTEM_NAME "iOS")
    if (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleSimulator")
      set (CMAKE_OSX_SYSROOT "iphonesimulator")
    elseif (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleOS")
      set (CMAKE_OSX_SYSROOT "iphoneos")
    elseif (HASILWGDF_PLATFORM_VARIANT STREQUAL "AppleAll")
      set (CMAKE_IOS_INSTALL_COMBINED YES)
    else ()
      message (FATAL_ERROR "Variation \"${HASILWGDF_PLATFORM_VARIANT}\" for platform \"${HASILWGDF_PLATFORM}\" is not supported.")
    endif ()
  elseif (HASILWGDF_PLATFORM STREQUAL "macOS")
    set (CMAKE_SYSTEM_NAME "Darwin")
    if (HASILWGDF_PLATFORM_VARIANT NOT STREQUAL "")
      message (FATAL_ERROR "Variation \"${HASILWGDF_PLATFORM_VARIANT}\" for platform \"${HASILWGDF_PLATFORM}\" is not supported.")
    endif ()
  else ()
    message (FATAL_ERROR "Unable to use generator \"${CURRENT_GEN}\" with platform \"${HASILWGDF_PLATFORM}\".")
  endif ()
else ()
  message (FATAL_ERROR "Invalid or unsupported generator. Please use one of these: MinGW Makefiles, MSYS Makefiles, Ninja, Unix Makefiles, Visual Studio (12+), Xcode")
endif ()
